# Generated by Django 6.0 on 2025-12-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
