# Generated by Django 6.0 on 2025-12-31 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0002_item_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approved_for_formulas',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_good', models.OneToOneField(limit_choices_to={'item_type': 'finished_good'}, on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='erp_core.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormulaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='erp_core.formula')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_ingredients', to='erp_core.item')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('formula', 'item')},
            },
        ),
    ]
