# Generated by Django 6.0 on 2025-12-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0003_item_approved_for_formulas_formula_formulaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='quantity_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='spills',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='variance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='wastes',
            field=models.FloatField(default=0.0),
        ),
    ]
