# Generated by Django 6.0 on 2026-01-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0004_productionbatch_closed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pack_size',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_item_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='quantity_actual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='variance',
            field=models.FloatField(default=0.0),
        ),
    ]
