# Generated by Django 6.0 on 2026-01-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0005_item_pack_size_item_price_item_vendor_item_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='qc_actual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='qc_initials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='qc_parameters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
