# Generated by Django 6.0 on 2026-01-05 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0007_invoice_journalentry_account_invoiceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('vendor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('risk_profile', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('on_time_performance', models.FloatField(default=100.0)),
                ('quality_complaints', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='formula',
            name='equipment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='mixing_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='order_of_addition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='vendor_lot_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='QualityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_parameter', models.CharField(max_length=255)),
                ('test_result', models.CharField(max_length=255)),
                ('pass_fail', models.BooleanField()),
                ('tested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_tests', to='erp_core.productionbatch')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_tests', to='erp_core.lot')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('quality_complaint', 'Quality Complaint'), ('on_time_issue', 'On-Time Delivery Issue'), ('approval_change', 'Approval Status Change'), ('risk_change', 'Risk Profile Change'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='erp_core.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Histories',
                'ordering': ['-date'],
            },
        ),
    ]
