# Generated by Django 6.0 on 2026-01-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0009_lot_on_hold_lot_shipment_status_rejectedshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='landed_cost',
            field=models.FloatField(blank=True, help_text='Landed cost per unit', null=True),
        ),
    ]
