# Generated by Django 6.0 on 2026-01-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0011_costmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='freight_actual',
            field=models.FloatField(blank=True, help_text='Actual freight cost per unit (in item unit of measure)', null=True),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='freight_per_kg',
            field=models.FloatField(default=0.0, help_text='Freight estimate per kg'),
        ),
    ]
