# Generated by Django 6.0 on 2026-01-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0012_lot_freight_actual_alter_costmaster_freight_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bioterrorism_act_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bioterrorism_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ctpat_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fsma_compliant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gfsi_certificate_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gfsi_certification_body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gfsi_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='risk_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='risk_assessment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='risk_tier',
            field=models.CharField(blank=True, choices=[('tier_1', 'Tier 1 - Highest Risk'), ('tier_2', 'Tier 2 - Standard Risk'), ('tier_3', 'Tier 3 - Low Risk')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SupplierSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='not_started', max_length=20)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('company_info', models.JSONField(blank=True, default=dict)),
                ('compliance_responses', models.JSONField(blank=True, default=dict)),
                ('quality_program_responses', models.JSONField(blank=True, default=dict)),
                ('food_security_responses', models.JSONField(blank=True, default=dict)),
                ('see_program_responses', models.JSONField(blank=True, default=dict)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='erp_core.vendor')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_commodity', models.CharField(max_length=255)),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('intended_use', models.TextField()),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('justification', models.TextField()),
                ('risk_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('requested_by', models.CharField(max_length=100)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='erp_core.vendor')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certificate_of_insurance', 'Certificate of Insurance'), ('letter_of_guarantee', 'Letter of Guarantee'), ('third_party_audit', 'Third-Party Audit Certificate'), ('recall_plan', 'Recall and Traceability Plan'), ('traceability_program', 'Traceability Program'), ('code_of_conduct', 'Code of Conduct'), ('gfsi_certificate', 'GFSI Certificate'), ('fsma_statement', 'FSMA Statement'), ('haccp_plan', 'HACCP Plan'), ('food_defense_statement', 'Food Defense Statement'), ('spec_sheet', 'Spec Sheet'), ('sds', 'Safety Data Sheet (SDS)'), ('nutritional_info', 'Nutritional Information'), ('allergen_statement', 'Allergen Statement'), ('halal_certificate', 'Halal Certificate'), ('kosher_certificate', 'Kosher Certificate'), ('other', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.BinaryField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='erp_core.vendor')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['vendor', 'document_type'], name='erp_core_su_vendor__4aed55_idx'), models.Index(fields=['expiration_date'], name='erp_core_su_expirat_11f467_idx')],
            },
        ),
    ]
