# Generated by Django 6.0 on 2026-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0013_vendor_bioterrorism_act_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_order',
            field=models.FloatField(default=0.0, help_text='Quantity currently on order'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='coa_sds_email',
            field=models.EmailField(blank=True, help_text='Email for CoA and SDS', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(blank=True, help_text='Internal order number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_address',
            field=models.CharField(default='6431 Michels Dr.', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_city',
            field=models.CharField(default='Washington', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_name',
            field=models.CharField(default='Wildwood Ingredients, LLC', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_state',
            field=models.CharField(default='MO', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_zip',
            field=models.CharField(default='63090', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_terms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_type',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer')], default='vendor', max_length=20),
        ),
    ]
