# Generated by Django 6.0 on 2026-01-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0014_item_on_order_purchaseorder_coa_sds_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='actual_ship_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_po_number',
            field=models.CharField(blank=True, help_text='Customer Purchase Order Number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='freight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='grand_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='misc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='prepaid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='requested_ship_date',
            field=models.DateTimeField(blank=True, help_text='REQ SHIP DATE from customer PO', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='vendor_part_number',
            field=models.CharField(blank=True, help_text='Vendor Part No from customer PO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
