# Generated by Django 6.0 on 2026-01-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0015_salesorder_actual_ship_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedPONumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='PONumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prefix', models.CharField(max_length=6, unique=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_prefix', '-sequence_number'],
            },
        ),
    ]
