# Generated by Django 6.0 on 2026-01-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0016_issuedponumber_ponumbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='required_date',
            field=models.DateField(blank=True, help_text='Required delivery date from PO creation', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Expected delivery date (auto-updated from tracking)', null=True),
        ),
    ]
