# Generated by Django 6.0 on 2026-01-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0017_purchaseorder_carrier_purchaseorder_required_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='original_po',
            field=models.ForeignKey(blank=True, help_text='Original PO if this is a revision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='erp_core.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='revision_number',
            field=models.IntegerField(default=0, help_text='Revision number (0 = original, 1+ = revisions)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
