# Generated by Django 6.0 on 2026-01-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0019_remove_account_parent_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_material', models.CharField(db_index=True, max_length=255)),
                ('wwi_product_code', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price_per_kg', models.FloatField(blank=True, null=True)),
                ('price_per_lb', models.FloatField(blank=True, null=True)),
                ('incoterms', models.CharField(blank=True, choices=[('CIF', 'CIF'), ('FCA', 'FCA'), ('EXW', 'EXW'), ('CIP', 'CIP'), ('FOB', 'FOB'), ('DDP', 'DDP'), ('DAP', 'DAP')], max_length=50, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('hts_code', models.CharField(blank=True, max_length=50, null=True)),
                ('tariff', models.FloatField(default=0.0)),
                ('freight_per_kg', models.FloatField(default=0.0, help_text='Freight estimate per kg')),
                ('cert_cost_per_kg', models.FloatField(default=0.0)),
                ('landed_cost_per_kg', models.FloatField(blank=True, null=True)),
                ('landed_cost_per_lb', models.FloatField(blank=True, null=True)),
                ('margin', models.FloatField(blank=True, null=True)),
                ('selling_price_per_kg', models.FloatField(blank=True, null=True)),
                ('selling_price_per_lb', models.FloatField(blank=True, null=True)),
                ('strength', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_time', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor_material', 'wwi_product_code'],
                'indexes': [models.Index(fields=['wwi_product_code'], name='erp_core_co_wwi_pro_1206f4_idx'), models.Index(fields=['vendor'], name='erp_core_co_vendor_a032b2_idx'), models.Index(fields=['vendor_material'], name='erp_core_co_vendor__b613cf_idx')],
            },
        ),
    ]
