# Generated by Django 6.0 on 2026-01-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0021_purchaseorder_carrier_purchaseorder_coa_sds_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='risk_profile',
            field=models.CharField(choices=[('1', '1 - Low Risk'), ('2', '2 - Medium Risk'), ('3', '3 - High Risk')], default='2', max_length=20),
        ),
    ]
