# Generated by Django 6.0 on 2026-01-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0022_alter_vendor_risk_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pack_size',
            field=models.FloatField(blank=True, help_text='Pack size in the unit of measure', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, help_text='Price per unit of measure', null=True),
        ),
    ]
