# Generated by Django 6.0 on 2026-01-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0023_item_pack_size_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_order',
            field=models.FloatField(default=0.0, help_text='Quantity currently on order'),
        ),
        migrations.AddField(
            model_name='lot',
            name='on_hold',
            field=models.BooleanField(default=False, help_text='Lot is on hold and not available for use'),
        ),
    ]
