# Generated by Django 6.0 on 2026-01-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0025_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='freight_actual',
            field=models.FloatField(blank=True, help_text='Actual freight cost for this lot', null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase order number associated with this lot', max_length=100, null=True),
        ),
    ]
