# Generated by Django 6.0 on 2026-01-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0026_add_freight_actual_po_number_to_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='accepted', help_text='Acceptance status of the lot', max_length=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='on_hold',
            field=models.BooleanField(default=False, help_text='Lot is on hold and not available for use (deprecated - use status instead)'),
        ),
    ]
