# Generated by Django 6.0 on 2026-01-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0027_add_status_to_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='short_reason',
            field=models.CharField(blank=True, help_text='Reason for short shipment (damage, short shipped, etc.)', max_length=255, null=True),
        ),
    ]
