# Generated by Django 6.0 on 2026-01-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0028_add_short_reason_to_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostMasterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.FloatField(blank=True, null=True)),
                ('price_per_lb', models.FloatField(blank=True, null=True)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Reason for price change', null=True)),
                ('cost_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='erp_core.costmaster')),
            ],
            options={
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['cost_master', '-effective_date'], name='erp_core_co_cost_ma_d1d260_idx')],
            },
        ),
    ]
