# Generated by Django 6.0 on 2026-01-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0029_remove_purchaseorderitem_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sku', 'vendor']},
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('sku', 'vendor')},
        ),
    ]
