# Generated by Django 6.0 on 2026-01-08 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0030_alter_item_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField(blank=True, help_text='Physical state, color, odor, etc.', null=True)),
                ('color_specification', models.TextField(blank=True, help_text='CV, dye %, color strength, etc.', null=True)),
                ('ph', models.CharField(blank=True, max_length=50, null=True)),
                ('water_activity', models.CharField(blank=True, help_text='aW', max_length=50, null=True)),
                ('microbiological_requirements', models.TextField(blank=True, help_text='If micro testing not required, rationale must be provided', null=True)),
                ('shelf_life_storage', models.TextField(blank=True, help_text='Temperature data, Basis for decision, Shelf-Life Assignment Form (Doc No. 5.1.4–03), Shelf-Life Study Log (Doc No. 5.1.4–02)', null=True)),
                ('packaging_type', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_criteria', models.TextField(blank=True, help_text='Physical parameter testing, flavor profile, customer considerations, etc.', null=True)),
                ('msds_created', models.BooleanField(default=False)),
                ('commercial_spec_created', models.BooleanField(default=False, help_text='COA')),
                ('label_template_created', models.BooleanField(default=False)),
                ('micro_growth_evaluated', models.BooleanField(default=False)),
                ('kosher_letter_added', models.BooleanField(default=False)),
                ('haccp_plan_created', models.BooleanField(default=False)),
                ('processing_requirements', models.TextField(blank=True, help_text='Specific tank or mixer, mixing time, allergen considerations, temperature requirements', null=True)),
                ('completed_by_name', models.CharField(blank=True, help_text='Name and Title of Person Completing Form', max_length=255, null=True)),
                ('completed_by_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('test_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('fps_pdf', models.FileField(blank=True, null=True, upload_to='fps_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(limit_choices_to={'item_type': 'finished_good'}, on_delete=django.db.models.deletion.CASCADE, related_name='fps', to='erp_core.item')),
            ],
            options={
                'verbose_name': 'Finished Product Specification',
                'verbose_name_plural': 'Finished Product Specifications',
            },
        ),
    ]
