# Generated by Django 6.0 on 2026-01-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0031_remove_purchaseorderitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_prefix', models.CharField(max_length=2, unique=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year_prefix', '-sequence_number'],
            },
        ),
        migrations.AddField(
            model_name='PONumberSequence',
            name='year_prefix',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='PONumberSequence',
            name='date_prefix',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterModelOptions(
            name='PONumberSequence',
            options={'ordering': ['-year_prefix', '-sequence_number']},
        ),
        migrations.CreateModel(
            name='SalesOrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_prefix', models.CharField(max_length=2, unique=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year_prefix', '-sequence_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='lotnumbersequence',
            options={'ordering': ['-year_prefix', '-sequence_number']},
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='lotnumbersequence',
            name='year_prefix',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_reference_number',
            field=models.CharField(blank=True, help_text='Customer PO number or reference number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lotnumbersequence',
            name='date_prefix',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
