# Generated by Django 6.0 on 2026-01-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0032_invoicenumbersequence_ponumbersequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='vendor_lot_number',
            field=models.CharField(blank=True, help_text='Vendor lot number from check-in form', max_length=100, null=True),
        ),
    ]
