# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0063_lot_depleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('natural_colors', 'Natural Colors'),
                    ('synthetic_colors', 'Synthetic Colors'),
                    ('antioxidants', 'Antioxidants'),
                    ('other', 'Other'),
                ],
                help_text='Product category: Natural Colors, Synthetic Colors, Antioxidants, or Other',
                max_length=50,
                null=True
            ),
        ),
    ]
