# Generated by Django 5.2.12 on 2026-04-09 14:59
#
# Deliberate plan: models and SQLite (wwi_erp.db) diverged — finance tables and
# several columns were added outside the migration graph. A plain autogenerated
# migration would try to CREATE existing tables and fail.
#
# 1) RunPython: minimal real DDL on SQLite only (legacy salesorder.customer_id
#    varchar → preserve as legacy_customer_ref, add integer FK customer_id;
#    drop removed invoice/PO fields; add missing item/contact columns).
# 2) SeparateDatabaseAndState: advance Django's migration state to match
#    models.py without issuing duplicate CREATE TABLE / AddField SQL.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _sqlite_column_names(cursor, table):
    cursor.execute('PRAGMA table_info(%s)' % table)
    return {row[1] for row in cursor.fetchall()}


def align_sqlite_schema_with_models(apps, schema_editor):
    """SQLite-only physical fixes before state sync (no-op on other backends)."""
    connection = schema_editor.connection
    if connection.vendor != 'sqlite':
        return
    cursor = connection.cursor()

    # --- SalesOrder: legacy string customer_id vs ForeignKey customer_id ---
    so_cols = _sqlite_column_names(cursor, 'erp_core_salesorder')
    if 'customer_id' in so_cols and 'legacy_customer_ref' not in so_cols:
        cursor.execute(
            """
            UPDATE erp_core_salesorder
            SET customer_legacy_id = customer_id
            WHERE (customer_legacy_id IS NULL OR TRIM(COALESCE(customer_legacy_id, '')) = '')
              AND customer_id IS NOT NULL AND TRIM(COALESCE(customer_id, '')) != ''
            """
        )
        cursor.execute(
            'ALTER TABLE erp_core_salesorder RENAME COLUMN customer_id TO legacy_customer_ref'
        )
        cursor.execute(
            'ALTER TABLE erp_core_salesorder ADD COLUMN customer_id INTEGER NULL '
            'REFERENCES erp_core_customer (id)'
        )

    # --- Invoice: column removed from model ---
    inv_cols = _sqlite_column_names(cursor, 'erp_core_invoice')
    if 'customer_vendor_id' in inv_cols:
        try:
            cursor.execute('ALTER TABLE erp_core_invoice DROP COLUMN customer_vendor_id')
        except Exception:
            pass

    # Non-null due_date in model: backfill stragglers
    cursor.execute(
        'UPDATE erp_core_invoice SET due_date = invoice_date '
        'WHERE due_date IS NULL AND invoice_date IS NOT NULL'
    )

    # --- PONumberSequence: date_prefix removed from model ---
    po_seq_cols = _sqlite_column_names(cursor, 'erp_core_ponumbersequence')
    if 'date_prefix' in po_seq_cols:
        try:
            cursor.execute('ALTER TABLE erp_core_ponumbersequence DROP COLUMN date_prefix')
        except Exception:
            pass

    # --- CustomerContact flags ---
    cc_cols = _sqlite_column_names(cursor, 'erp_core_customercontact')
    if 'is_ap_contact' not in cc_cols:
        cursor.execute(
            'ALTER TABLE erp_core_customercontact ADD COLUMN is_ap_contact bool NOT NULL DEFAULT 0'
        )
    if 'is_purchasing_contact' not in cc_cols:
        cursor.execute(
            'ALTER TABLE erp_core_customercontact ADD COLUMN is_purchasing_contact bool NOT NULL DEFAULT 0'
        )

    # --- Item tariff / customs fields ---
    item_cols = _sqlite_column_names(cursor, 'erp_core_item')
    if 'country_of_origin' not in item_cols:
        cursor.execute(
            'ALTER TABLE erp_core_item ADD COLUMN country_of_origin varchar(255) NULL'
        )
    if 'hts_code' not in item_cols:
        cursor.execute('ALTER TABLE erp_core_item ADD COLUMN hts_code varchar(50) NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0097_remove_allow_fg_without_repack_backfill_fg_category'),
    ]

    operations = [
        migrations.RunPython(align_sqlite_schema_with_models, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.FloatField(default=0.0, help_text='Opening balance at start of period')),
                ('period_debits', models.FloatField(default=0.0)),
                ('period_credits', models.FloatField(default=0.0)),
                ('closing_balance', models.FloatField(default=0.0, help_text='Closing balance at end of period')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account', 'fiscal_period'],
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, help_text='Customer name', max_length=255)),
                ('customer_id', models.CharField(blank=True, help_text='Customer ID if available', max_length=100, null=True)),
                ('invoice_date', models.DateField(help_text='Date of invoice')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('original_amount', models.FloatField(help_text='Original invoice amount')),
                ('amount_paid', models.FloatField(default=0.0, help_text='Amount paid so far')),
                ('balance', models.FloatField(help_text='Outstanding balance (original_amount - amount_paid)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Accounts Receivable',
                'ordering': ['due_date', 'customer_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_period', models.CharField(help_text='Period identifier (e.g., "2025-Q1", "2025-01")', max_length=20)),
                ('forecast_quantity', models.FloatField(help_text='Forecasted quantity')),
                ('unit_of_measure', models.CharField(choices=[('lbs', 'Pounds'), ('kg', 'Kilograms'), ('ea', 'Each')], default='lbs', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-forecast_period', 'item__sku'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('unit_of_measure', models.CharField(choices=[('lbs', 'Pounds'), ('kg', 'Kilograms'), ('ea', 'Each')], default='lbs', max_length=10)),
                ('incoterms', models.CharField(blank=True, help_text='Incoterms for this item (e.g. FOB, CIF, DAP)', max_length=30, null=True)),
                ('incoterms_place', models.CharField(blank=True, help_text='Place/point for the incoterm (e.g. New York for CIF New York)', max_length=100, null=True)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['customer', 'item', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(db_index=True)),
                ('debit_credit', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'General Ledger Entries',
                'ordering': ['entry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPackSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_size', models.FloatField(help_text='Pack size value (e.g., 2000, 5)')),
                ('pack_size_unit', models.CharField(choices=[('lbs', 'Pounds'), ('kg', 'Kilograms'), ('gal', 'Gallons'), ('ea', 'Each'), ('pcs', 'Pieces')], help_text='Unit for pack size (e.g., lbs, gal)', max_length=10)),
                ('price', models.FloatField(blank=True, help_text='Price per pack (optional, pack-size-specific pricing)', null=True)),
                ('description', models.CharField(blank=True, help_text='Description of pack size (e.g., "2000lb IBC", "5 gallon pail")', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default pack size for this item')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pack size is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Pack Size',
                'verbose_name_plural': 'Item Pack Sizes',
                'ordering': ['item', 'pack_size', 'pack_size_unit'],
            },
        ),
        migrations.CreateModel(
            name='LotDepletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(db_index=True, help_text='Snapshot of lot number at time of depletion', max_length=20)),
                ('item_sku', models.CharField(db_index=True, help_text='Item SKU at time of depletion', max_length=255)),
                ('item_name', models.CharField(help_text='Item name at time of depletion', max_length=255)),
                ('vendor', models.CharField(blank=True, help_text='Vendor at time of depletion', max_length=255, null=True)),
                ('initial_quantity', models.FloatField(help_text='Original quantity when lot was created')),
                ('quantity_before', models.FloatField(help_text='Quantity remaining before this transaction')),
                ('quantity_used', models.FloatField(help_text='Quantity used in this transaction')),
                ('final_quantity', models.FloatField(help_text='Quantity remaining after this transaction (should be 0 or negative)')),
                ('unit_of_measure', models.CharField(choices=[('lbs', 'Pounds'), ('kg', 'Kilograms'), ('ea', 'Each')], default='lbs', help_text='Unit of measure for quantities', max_length=10)),
                ('depletion_method', models.CharField(choices=[('production', 'Production Batch'), ('sales', 'Sales Order'), ('adjustment', 'Inventory Adjustment'), ('manual', 'Manual Depletion'), ('reversal', 'Reversal/Cancellation')], help_text='How the lot was depleted', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Batch number, SO number, etc.', max_length=100, null=True)),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference (batch_number, so_number, etc.)', max_length=50, null=True)),
                ('transaction_id', models.IntegerField(blank=True, help_text='Related InventoryTransaction ID if applicable', null=True)),
                ('batch_id', models.IntegerField(blank=True, help_text='Related ProductionBatch ID if applicable', null=True)),
                ('sales_order_id', models.IntegerField(blank=True, help_text='Related SalesOrder ID if applicable', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional context about the depletion', null=True)),
                ('depleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Lot Depletion Log',
                'verbose_name_plural': 'Lot Depletion Logs',
                'ordering': ['-depleted_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('ap_payment', 'Accounts Payable Payment'), ('ar_payment', 'Accounts Receivable Payment')], max_length=20)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('check', 'Check'), ('wire', 'Wire Transfer'), ('ach', 'ACH'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('amount', models.FloatField()),
                ('reference_number', models.CharField(blank=True, help_text='Check number, wire reference, etc.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_type', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('meeting', 'In-Person Meeting'), ('video', 'Video Call'), ('other', 'Other')], default='phone', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(help_text='Call notes, discussion points, outcomes')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, help_text='User who logged the call', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-call_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='accountspayable',
            new_name='erp_core_ac_vendor__490afb_idx',
            old_name='erp_core_ac_vendor_st_idx',
        ),
        migrations.RenameIndex(
            model_name='accountspayable',
            new_name='erp_core_ac_due_dat_86dcd2_idx',
            old_name='erp_core_ac_due_st_idx',
        ),
        migrations.RenameIndex(
            model_name='accountspayable',
            new_name='erp_core_ac_purchas_8ce188_idx',
            old_name='erp_core_ac_po_st_idx',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliation',
            new_name='erp_core_ba_account_8bfecd_idx',
            old_name='erp_core_ba_account_8a0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='fiscalperiod',
            new_name='erp_core_fi_start_d_6754c4_idx',
            old_name='erp_core_fp_dates_idx',
        ),
        migrations.RenameIndex(
            model_name='fiscalperiod',
            new_name='erp_core_fi_is_clos_dfa93e_idx',
            old_name='erp_core_fp_closed_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='erp_core_jo_entry_d_28f302_idx',
            old_name='erp_core_je_date_st_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='erp_core_jo_referen_b30134_idx',
            old_name='erp_core_je_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='erp_core_jo_fiscal__155eb7_idx',
            old_name='erp_core_je_fp_date_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentryline',
            new_name='erp_core_jo_account_611157_idx',
            old_name='erp_core_jel_ac_je_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentryline',
            new_name='erp_core_jo_journal_ec9c05_idx',
            old_name='erp_core_jel_je_dc_idx',
        ),
        migrations.RenameIndex(
            model_name='lotattributechangelog',
            new_name='erp_core_lo_changed_526cff_idx',
            old_name='lacg_changed_field_idx',
        ),
        migrations.RenameIndex(
            model_name='productionlog',
            new_name='erp_core_pr_logged__d2f602_idx',
            old_name='erp_core_p_logged__idx',
        ),
        migrations.RenameIndex(
            model_name='productionlog',
            new_name='erp_core_pr_finishe_c58212_idx',
            old_name='erp_core_p_finishe_idx',
        ),
        migrations.RenameIndex(
            model_name='productionlog',
            new_name='erp_core_pr_closed__337a79_idx',
            old_name='erp_core_p_closed__idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderlog',
            new_name='erp_core_pu_logged__ece466_idx',
            old_name='erp_core_p_logged__idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderlog',
            new_name='erp_core_pu_vendor__203bbd_idx',
            old_name='erp_core_p_vendor__idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderlog',
            new_name='erp_core_pu_action_e497f7_idx',
            old_name='erp_core_p_action__idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderlog',
            new_name='erp_core_pu_lot_num_cced9f_idx',
            old_name='erp_core_p_lot_num_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorpricing',
            new_name='erp_core_ve_vendor__dbb048_idx',
            old_name='erp_core_v_vendor__idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_vendor_id',
        ),
        migrations.RemoveField(
            model_name='ponumbersequence',
            name='date_prefix',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='customercontact',
            name='is_ap_contact',
            field=models.BooleanField(default=False, help_text='A/P contact: receives invoices when issued'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='is_purchasing_contact',
            field=models.BooleanField(default=False, help_text='Purchasing contact: receives sales order confirmations when issued'),
        ),
        migrations.AddField(
            model_name='formula',
            name='qc_parameter_name',
            field=models.CharField(blank=True, help_text='QC parameter name (e.g., norbixin, betanin, absorbance)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='qc_spec_max',
            field=models.FloatField(blank=True, help_text='Maximum acceptable value for QC parameter', null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='qc_spec_min',
            field=models.FloatField(blank=True, help_text='Minimum acceptable value for QC parameter', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='erp_core.salesorder'),
        ),
        migrations.AddField(
            model_name='item',
            name='country_of_origin',
            field=models.CharField(blank=True, help_text='Country of origin for tariff calculation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='hts_code',
            field=models.CharField(blank=True, help_text='HTS (Harmonized Tariff Schedule) code for tariff calculation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='unit_of_measure',
            field=models.CharField(choices=[('lbs', 'Pounds'), ('kg', 'Kilograms'), ('ea', 'Each')], default='lbs', help_text='Unit of measure for quantities', max_length=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='actual_ship_date',
            field=models.DateTimeField(blank=True, help_text='Actual ship date', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer from customer database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='erp_core.customer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_address',
            field=models.TextField(blank=True, help_text='Legacy field - use ship_to_location when possible', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_city',
            field=models.CharField(blank=True, help_text='Legacy field - use ship_to_location when possible', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_country',
            field=models.CharField(blank=True, help_text='Legacy field - use ship_to_location when possible', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_legacy_id',
            field=models.CharField(blank=True, help_text='Customer ID (legacy field, deprecated - use customer FK)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Legacy field - use ship_to_location when possible', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_state',
            field=models.CharField(blank=True, help_text='Legacy field - use ship_to_location when possible', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_zip',
            field=models.CharField(blank=True, help_text='Legacy field - use ship_to_location when possible', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='ship_to_location',
            field=models.ForeignKey(blank=True, help_text='Ship-to location for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='erp_core.shiptolocation'),
        ),
        migrations.AlterField(
            model_name='checkinlog',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='Expiration date for the lot as recorded at check-in (snapshot)', null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('production', 'Production'), ('production_input', 'Production Input'), ('production_output', 'Production Output'), ('repack_input', 'Repack Input'), ('repack_output', 'Repack Output'), ('indirect_material_consumption', 'Indirect Material Consumption'), ('indirect_material_checkout', 'Indirect Material Checkout')], max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_vendor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(help_text='Calculated from invoice_date + payment_terms'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('customer', 'Customer Invoice'), ('vendor', 'Vendor Bill')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='pack_size',
            field=models.FloatField(blank=True, help_text='Legacy field - use ItemPackSize model instead', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, help_text='Legacy field - use ItemPackSize model instead', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor_item_number',
            field=models.CharField(blank=True, help_text='Vendor catalog / part number (shown on POs and item lists next to vendor name).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_number',
            field=models.CharField(blank=True, db_index=True, help_text='Lot number - generated on batch closure, or vendor_lot_number for raw materials', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lottransactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('production_input', 'Production Input'), ('production_output', 'Production Output'), ('repack_input', 'Repack Input'), ('repack_output', 'Repack Output'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('allocation', 'Allocation'), ('deallocation', 'Deallocation'), ('manual', 'Manual'), ('reversal', 'Reversal/Cancellation'), ('indirect_material_consumption', 'Indirect Material Consumption'), ('indirect_material_checkout', 'Indirect Material Checkout')], help_text='Type of transaction', max_length=30),
        ),
        migrations.AlterField(
            model_name='ponumbersequence',
            name='year_prefix',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='erp_core.productionbatch'),
        ),
        migrations.AlterField(
            model_name='rdformulaline',
            name='description',
            field=models.CharField(blank=True, help_text='Display name when no item or override (e.g. Beet Powder 0.8% (Nutracean))', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_name',
            field=models.CharField(help_text='Customer name (legacy field, use customer FK when possible)', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='expected_ship_date',
            field=models.DateTimeField(blank=True, help_text='Requested ship date', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, help_text='Legacy field - use street_address, city, state, country instead', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='service_vendor_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('customs_broker', 'Customs Broker'), ('freight_forwarder', 'Freight Forwarder')], help_text='Type of service vendor', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='lottransactionlog',
            index=models.Index(fields=['-logged_at', 'lot_number'], name='erp_core_lo_logged__5b8cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='lottransactionlog',
            index=models.Index(fields=['item_sku', '-logged_at'], name='erp_core_lo_item_sk_b9a5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='lottransactionlog',
            index=models.Index(fields=['transaction_type', '-logged_at'], name='erp_core_lo_transac_f4d1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='lottransactionlog',
            index=models.Index(fields=['reference_number', '-logged_at'], name='erp_core_lo_referen_322031_idx'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='erp_core.account'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='fiscal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balances', to='erp_core.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='account',
            field=models.ForeignKey(blank=True, help_text='AR account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_entries', to='erp_core.account'),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='invoice',
            field=models.ForeignKey(help_text='Related invoice', on_delete=django.db.models.deletion.CASCADE, related_name='ar_entries', to='erp_core.invoice'),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry created for this AR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_entries', to='erp_core.journalentry'),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Related sales order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_entries', to='erp_core.salesorder'),
        ),
        migrations.AddField(
            model_name='customerforecast',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='erp_core.customer'),
        ),
        migrations.AddField(
            model_name='customerforecast',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_forecasts', to='erp_core.item'),
        ),
        migrations.AddField(
            model_name='customerpricing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='erp_core.customer'),
        ),
        migrations.AddField(
            model_name='customerpricing',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_pricing', to='erp_core.item'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='erp_core.account'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='erp_core.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='erp_core.journalentry'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='journal_entry_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='erp_core.journalentryline'),
        ),
        migrations.AddField(
            model_name='itempacksize',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_sizes', to='erp_core.item'),
        ),
        migrations.AddField(
            model_name='lot',
            name='pack_size',
            field=models.ForeignKey(blank=True, help_text='Pack size for this lot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='erp_core.itempacksize'),
        ),
        migrations.AddField(
            model_name='lotdepletionlog',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depletion_logs', to='erp_core.lot'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Cash/bank account used for payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='erp_core.account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ap_entry',
            field=models.ForeignKey(blank=True, help_text='AP entry being paid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp_core.accountspayable'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ar_entry',
            field=models.ForeignKey(blank=True, help_text='AR entry being paid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp_core.accountsreceivable'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry created for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='erp_core.journalentry'),
        ),
        migrations.AddField(
            model_name='salescall',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_calls', to='erp_core.customercontact'),
        ),
        migrations.AddField(
            model_name='salescall',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_calls', to='erp_core.customer'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['account', 'fiscal_period'], name='erp_core_ac_account_6a84cc_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['fiscal_period', 'account'], name='erp_core_ac_fiscal__7d764a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('account', 'fiscal_period')},
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['customer_name', 'status'], name='erp_core_ac_custome_3289e2_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['due_date', 'status'], name='erp_core_ac_due_dat_9fb3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['invoice', 'status'], name='erp_core_ac_invoice_a73d72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerforecast',
            unique_together={('customer', 'item', 'forecast_period')},
        ),
        migrations.AddIndex(
            model_name='customerpricing',
            index=models.Index(fields=['customer', 'item', 'is_active'], name='erp_core_cu_custome_ddcdf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerpricing',
            unique_together={('customer', 'item', 'effective_date')},
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['account', 'entry_date'], name='erp_core_ge_account_19d9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['entry_date', 'fiscal_period'], name='erp_core_ge_entry_d_540cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['journal_entry', 'account'], name='erp_core_ge_journal_4bf681_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itempacksize',
            unique_together={('item', 'pack_size', 'pack_size_unit')},
        ),
        migrations.AddIndex(
            model_name='lotdepletionlog',
            index=models.Index(fields=['-depleted_at', 'lot_number'], name='erp_core_lo_deplete_8047d8_idx'),
        ),
        migrations.AddIndex(
            model_name='lotdepletionlog',
            index=models.Index(fields=['item_sku', '-depleted_at'], name='erp_core_lo_item_sk_21b28f_idx'),
        ),
        migrations.AddIndex(
            model_name='lotdepletionlog',
            index=models.Index(fields=['depletion_method', '-depleted_at'], name='erp_core_lo_depleti_5f7ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'payment_date'], name='erp_core_pa_payment_a28b82_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ap_entry', 'payment_date'], name='erp_core_pa_ap_entr_0e643e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ar_entry', 'payment_date'], name='erp_core_pa_ar_entr_87940b_idx'),
        ),
            ],
        ),
    ]
