# Generated by Django 5.2.12 on 2026-04-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0098_sync_models_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sku_pack_suffix',
            field=models.CharField(blank=True, help_text='Pack segment when present, e.g. L0040 or K0920. Null for master / parent-only rows.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sku_parent_code',
            field=models.CharField(blank=True, db_index=True, help_text='Material family code (e.g. D1307, P2408). Set automatically from SKU when parseable.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sku_parent_item',
            field=models.ForeignKey(blank=True, help_text='Optional link to the master item row for this family (same vendor when possible).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_variant_items', to='erp_core.item'),
        ),
    ]
