# Generated by Django 5.2.12 on 2026-04-10 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0101_snap_production_batch_input_quantities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCoaTestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('test_name', models.CharField(max_length=255)),
                ('specification_text', models.TextField(help_text='Shown in the COA Specification column')),
                ('result_kind', models.CharField(choices=[('numeric_range', 'Numeric range (min–max)'), ('numeric_minimum', 'Numeric minimum (e.g. NLT)'), ('pass_fail', 'Pass / fail (text)'), ('text_only', 'Text only (no auto pass/fail)')], default='text_only', max_length=32)),
                ('numeric_min', models.FloatField(blank=True, help_text='For numeric_minimum or numeric_range', null=True)),
                ('numeric_max', models.FloatField(blank=True, help_text='For numeric_range only', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(limit_choices_to={'item_type__in': ['finished_good', 'distributed_item']}, on_delete=django.db.models.deletion.CASCADE, related_name='coa_test_lines', to='erp_core.item')),
            ],
            options={
                'verbose_name': 'Item COA test line',
                'verbose_name_plural': 'Item COA test lines',
                'ordering': ['item', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LotCoaCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_po', models.CharField(blank=True, default='', max_length=120)),
                ('qc_parameter_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('qc_spec_min_snapshot', models.FloatField(blank=True, null=True)),
                ('qc_spec_max_snapshot', models.FloatField(blank=True, null=True)),
                ('qc_result_value', models.FloatField(blank=True, null=True)),
                ('qc_result_pass', models.BooleanField(blank=True, null=True)),
                ('coa_pdf', models.FileField(blank=True, null=True, upload_to='coa_pdfs/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coa_certificate', to='erp_core.lot')),
            ],
            options={
                'verbose_name': 'Lot COA certificate',
                'verbose_name_plural': 'Lot COA certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='LotCoaLineResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('specification_text', models.TextField()),
                ('result_text', models.CharField(max_length=500)),
                ('passes', models.BooleanField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_results', to='erp_core.lotcoacertificate')),
                ('item_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_results', to='erp_core.itemcoatestline')),
            ],
            options={
                'verbose_name': 'Lot COA line result',
                'verbose_name_plural': 'Lot COA line results',
                'ordering': ['id'],
            },
        ),
    ]
