# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0103_lot_coa_customer_copy_quantity_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='piece_dimensions',
            field=models.JSONField(
                blank=True,
                help_text='List of dimension strings, one per handling unit (same length as pieces)',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='dimensions',
            field=models.TextField(
                blank=True,
                help_text='Human-readable summary; per-piece values in piece_dimensions',
                null=True,
            ),
        ),
    ]
