# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0104_shipment_piece_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='piece_weights',
            field=models.JSONField(
                blank=True,
                help_text='List of weight strings per handling unit (same length as pieces), e.g. "45 lbs"',
                null=True,
            ),
        ),
    ]
