# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0105_shipment_piece_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='shelf_life_months',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Default shelf life in months from batch close / lot receipt; used to set expiration on new FG output lots.',
                null=True,
            ),
        ),
    ]
