# Generated by Django — combined checkout for multiple sales orders

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_core", "0108_backfill_customer_bill_to_from_hq"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="combined_shipment_key",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="When set, links multiple shipments checked out together (one truck, shared packing list).",
                null=True,
            ),
        ),
    ]
