# Generated by Django 5.2.12 on 2026-08-04 04:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0109_shipment_combined_shipment_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_prefix', models.CharField(max_length=2, unique=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year_prefix', '-sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='CustomerQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted')], default='draft', max_length=20)),
                ('quote_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('customer_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='erp_core.customercontact')),
                ('converted_sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotes', to='erp_core.salesorder')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='erp_core.customer')),
                ('ship_to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='erp_core.shiptolocation')),
            ],
            options={
                'ordering': ['-quote_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('unit_of_measure', models.CharField(choices=[('lbs', 'Pounds'), ('kg', 'Kilograms'), ('ea', 'Each')], default='lbs', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_quote_items', to='erp_core.item')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp_core.customerquote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
