# Generated by Django 5.2.12 on 2026-08-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0111_rd_formula_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingWhatIfLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('close_probability', models.FloatField(default=0.0, help_text='0–1 close probability')),
                ('source_type', models.CharField(choices=[('distributed', 'Distributed'), ('manufactured', 'Manufactured')], default='distributed', max_length=20)),
                ('product_name', models.CharField(blank=True, default='', help_text='Product label used to look up Cost Master / R&D formula cost', max_length=255)),
                ('base_cost_per_lb', models.FloatField(blank=True, help_text='Looked-up or manual base $/lb before additional cost', null=True)),
                ('cost_is_manual', models.BooleanField(default=False, help_text='If true, base_cost_per_lb is user-entered and not auto-refreshed')),
                ('additional_cost_per_lb', models.FloatField(default=0.0)),
                ('margin', models.FloatField(blank=True, help_text='Target margin as fraction (e.g. 0.30 = 30%)', null=True)),
                ('volume_lb', models.FloatField(blank=True, help_text='Annual volume in lb', null=True)),
                ('volume_pct_target', models.FloatField(blank=True, help_text='% of volume expected to hit target year (0–1)', null=True)),
                ('agreement', models.CharField(blank=True, choices=[('', '—'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('lost', 'Lost'), ('hold', 'On hold')], default='', max_length=20)),
                ('incoterms', models.CharField(blank=True, default='', max_length=100)),
                ('first_order_ship', models.CharField(blank=True, default='', max_length=100)),
                ('order_pattern', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatif_lines', to='erp_core.costmaster')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_whatif_lines', to='erp_core.customer')),
                ('rd_formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatif_lines', to='erp_core.rdformula')),
            ],
            options={
                'verbose_name': 'Pricing what-if line',
                'verbose_name_plural': 'Pricing what-if lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
