# Generated by Django 5.2.12 on 2026-08-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0114_rd_formula_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdformula',
            name='name',
            field=models.CharField(help_text='Commercial product name wording (e.g. Natural Green). Trial/description details go in notes.', max_length=255),
        ),
    ]
