# Generated by Django 5.2.12 on 2026-08-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0115_rd_formula_name_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingwhatifline',
            name='catalog_key',
            field=models.CharField(blank=True, default='', help_text='Stable catalog id, e.g. cm:12 or rd:5', max_length=64),
        ),
        migrations.AddField(
            model_name='pricingwhatifline',
            name='ingredient_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-formula-line cost overrides for what-if vendor / RM pricing'),
        ),
        migrations.AlterField(
            model_name='pricingwhatifline',
            name='source_type',
            field=models.CharField(choices=[('distributed', 'Distributed'), ('manufactured', 'Manufactured'), ('rd', 'R&D formula')], default='distributed', max_length=20),
        ),
        migrations.CreateModel(
            name='PricingWhatIfScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('overrides', models.JSONField(blank=True, default=dict, help_text='Ingredient price overrides: {"lines": {"<line_id>": {"price_per_lb": 1.2, "vendor_label": "..."}}}')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rd_formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatif_scenarios', to='erp_core.rdformula')),
            ],
            options={
                'verbose_name': 'Pricing what-if scenario',
                'verbose_name_plural': 'Pricing what-if scenarios',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pricingwhatifline',
            name='cost_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatif_lines', to='erp_core.pricingwhatifscenario'),
        ),
    ]
