# Generated by Django 5.2.12 on 2026-08-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0116_whatif_formula_overrides_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingwhatifline',
            name='freight_per_lb',
            field=models.FloatField(default=0.0, help_text='What-if freight-in $/lb. Coupled with freight_per_kg (×2.2). Not added on top of CM landed.'),
        ),
        migrations.AddField(
            model_name='pricingwhatifline',
            name='tariff_rate',
            field=models.FloatField(default=0.0, help_text='What-if tariff as decimal (0.381 = 38.1%). Applied to base_cost_per_lb; do not also use CM landed.'),
        ),
        migrations.AlterField(
            model_name='pricingwhatifline',
            name='base_cost_per_lb',
            field=models.FloatField(blank=True, help_text='Ex-works / formula base $/lb BEFORE what-if tariff and freight (not Cost Master landed).', null=True),
        ),
    ]
