# Generated by Django 5.2.12 on 2026-08-10 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0117_whatif_freight_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('count_type', models.CharField(choices=[('beginning_balance', 'Beginning balance'), ('annual_physical', 'Annual physical'), ('ad_hoc', 'Ad hoc count')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft / counting'), ('review', 'Variance review'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('count_date', models.DateField(help_text='As-of date for the physical count / beginning balance')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Inventory count session',
                'verbose_name_plural': 'Inventory count sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('customer', 'Customer Invoice'), ('vendor', 'Vendor Bill'), ('credit', 'Credit Memo')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number_snapshot', models.CharField(blank=True, default='', max_length=40)),
                ('sku_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('item_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('unit_of_measure', models.CharField(blank=True, default='lbs', max_length=10)),
                ('system_qty', models.FloatField(default=0.0, help_text='quantity_remaining frozen when the line was added (0 for new/found lots)')),
                ('counted_qty', models.FloatField(blank=True, help_text='Physical count; null until entered', null=True)),
                ('include_in_post', models.BooleanField(default=True, help_text='If false, line is left out when posting (variance kept on report only)')),
                ('is_new_lot', models.BooleanField(default=False, help_text='True for beginning-balance / found stock that creates a lot on post')),
                ('vendor_lot_number', models.CharField(blank=True, default='', max_length=100)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('line_notes', models.CharField(blank=True, default='', max_length=500)),
                ('posted', models.BooleanField(default=False)),
                ('posted_variance', models.FloatField(blank=True, help_text='counted - system at post time', null=True)),
                ('created_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_count_lines', to='erp_core.lot')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='erp_core.item')),
                ('lot', models.ForeignKey(blank=True, help_text='Existing lot being counted; null when creating a new lot on post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_lines', to='erp_core.lot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp_core.inventorycountsession')),
            ],
            options={
                'verbose_name': 'Inventory count line',
                'verbose_name_plural': 'Inventory count lines',
                'ordering': ['sku_snapshot', 'lot_number_snapshot', 'id'],
                'indexes': [models.Index(fields=['session', 'sku_snapshot'], name='erp_core_in_session_7a9ec1_idx')],
            },
        ),
    ]
