# Generated by Django 5.2.12 on 2026-08-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0118_inventory_count_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountline',
            name='on_hold_qty_snapshot',
            field=models.FloatField(default=0.0, help_text='quantity_on_hold (or full remaining if status on_hold) when line was added'),
        ),
        migrations.AddField(
            model_name='inventorycountline',
            name='on_hold_snapshot',
            field=models.BooleanField(default=False, help_text='True when the lot was on hold (full or partial) when added to the count'),
        ),
    ]
