# Generated by Django 5.2.12 on 2026-08-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0119_inventory_count_on_hold_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_of_lading',
            field=models.CharField(blank=True, default='', help_text='Bill of lading / ocean BL / master B/L when applicable.', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='destination_place',
            field=models.CharField(blank=True, default='', help_text='Place the ETA is relative to (plant, port, warehouse).', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='inbound_eta_date',
            field=models.DateField(blank=True, help_text='User-entered estimated arrival (manual tracking for now).', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipment_mode',
            field=models.CharField(blank=True, choices=[('', '—'), ('parcel', 'Parcel'), ('ltl', 'LTL / truck'), ('ocean', 'Ocean'), ('air', 'Air'), ('other', 'Other')], default='', help_text='Inbound shipment mode for tracking (parcel, LTL, ocean, …).', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_notes',
            field=models.TextField(blank=True, default='', help_text='Freeform tracking status notes from manual checks.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vessel_name',
            field=models.CharField(blank=True, default='', help_text='Vessel name for ocean freight (e.g. for MarineTraffic lookup).', max_length=255),
        ),
    ]
