# Generated by Django 5.2.12 on 2026-09-21 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0120_po_inbound_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_family',
            field=models.ForeignKey(blank=True, help_text='Commercial family code (e.g. D, L, HL) — used for sorting/filtering and aligned with R&D families.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='erp_core.rdformulafamily'),
        ),
    ]
