# Generated by Django 5.2.12 on 2026-09-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0122_seed_pigment_families_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotHoldCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('summary', models.CharField(blank=True, default='', help_text='Short reason shown in hold lists (e.g. drum damage).', max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.CharField(blank=True, default='', max_length=150)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=150)),
                ('resolution', models.CharField(blank=True, choices=[('accept', 'Accept (release to available)'), ('return', 'Return to vendor'), ('discard', 'Discard / scrap')], max_length=20, null=True)),
                ('resolution_qty', models.FloatField(blank=True, help_text='Quantity resolved in the closing action (native UoM).', null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_cases', to='erp_core.lot')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='LotHoldNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hold_photos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='erp_core.lotholdcase')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='lotholdcase',
            index=models.Index(fields=['status', '-opened_at'], name='erp_core_lo_status_c41cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='lotholdcase',
            index=models.Index(fields=['lot', 'status'], name='erp_core_lo_lot_id_469e60_idx'),
        ),
    ]
