# Generated by Django 5.2.12 on 2026-09-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0123_lot_hold_case_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('check_in', 'Check-In'), ('partial_check_in', 'Partial Check-In'), ('short_closed', 'Accepted Short / Closed Remaining'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20),
        ),
    ]
