# Generated by Django 5.2.12 on 2026-09-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0124_po_log_short_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('production', 'Production'), ('production_input', 'Production Input'), ('production_output', 'Production Output'), ('repack_input', 'Repack Input'), ('repack_output', 'Repack Output'), ('indirect_material_consumption', 'Indirect Material Consumption'), ('indirect_material_checkout', 'Indirect Material Checkout'), ('return', 'Customer Return Restock')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lottransactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('production_input', 'Production Input'), ('production_output', 'Production Output'), ('repack_input', 'Repack Input'), ('repack_output', 'Repack Output'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('allocation', 'Allocation'), ('deallocation', 'Deallocation'), ('manual', 'Manual'), ('reversal', 'Reversal/Cancellation'), ('indirect_material_consumption', 'Indirect Material Consumption'), ('indirect_material_checkout', 'Indirect Material Checkout'), ('return', 'Customer Return Restock')], help_text='Type of transaction', max_length=30),
        ),
    ]
