# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_core", "0125_txn_return_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulaitem",
            name="match_by_parent",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When True, batch tickets may use any pack-size SKU in this item's parent family "
                    "(sku_parent_code), including variants added later. When False, only this exact SKU."
                ),
            ),
        ),
    ]
