# Generated by Django 6.0 on 2026-09-24 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0139_lottransactionlog_po_vendor_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCoaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='Match FPS / lot COA line by name when catalog_test is empty.', max_length=255)),
                ('specification_text', models.TextField(blank=True, help_text='Printed Spec on this customer’s COA. Blank = use FPS Spec.', null=True)),
                ('include_on_customer_coa', models.BooleanField(blank=True, help_text='Null = use FPS On COA default.', null=True)),
                ('customer_result_display', models.CharField(blank=True, choices=[('', 'Use FPS default'), ('actual', 'Show actual'), ('pass_fail', 'Show Pass/Fail')], default='', help_text='Blank = use FPS Show as default.', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_requirements', to='erp_core.coatestcatalog')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coa_requirements', to='erp_core.customer')),
                ('item', models.ForeignKey(limit_choices_to={'item_type__in': ['finished_good', 'distributed_item']}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_coa_requirements', to='erp_core.item')),
            ],
            options={
                'verbose_name': 'Customer COA requirement',
                'verbose_name_plural': 'Customer COA requirements',
                'ordering': ['customer', 'item__sku', 'test_name'],
                'unique_together': {('customer', 'item', 'test_name')},
                'indexes': [
                    models.Index(fields=['customer', 'item', 'is_active'], name='erp_core_cu_custome_7a5f12_idx'),
                ],
            },
        ),
    ]
